---
title: "Bioinfoprojekt HeLa cells"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(ggpubr)
library(factoextra)
library(cluster)


MS_Table <- read.table("/Users/sinakuhnel/Desktop/Uni 1/FS4/Bioinfoprojekt/RDeeP_HeLa_NS.csv", header=TRUE, row.names=1, sep = ";")

#1. Clean Up and Normalization
#1.1 Split dataset into 2 datasets. One dataset consists only of Control group and the other of RNase.

ctrl.matrix= cbind(MS_Table[, seq(1,150,2)])
rnase.matrix=cbind(MS_Table[, seq(2,150,2)])


#1.2 Removing all zero rows
crep1=cbind(ctrl.matrix[,seq(1,75,3)])
crep2=cbind(ctrl.matrix[,seq(2,75,3)])
crep3=cbind(ctrl.matrix[,seq(3,75,3)])
rrep1=cbind(rnase.matrix[,seq(1,75,3)])
rrep2=cbind(rnase.matrix[,seq(2,75,3)])
rrep3=cbind(rnase.matrix[,seq(3,75,3)])

#creating vector (allzero) that contains all protein rows that consists only of zeros in at least one rep
#allzero contains 8 proteins that are deleted from the original reps
rmv.rows.crep1 = which(apply(crep1,1,function(x){sum(x)})==0)
rmv.rows.crep2 = which(apply(crep2,1,function(x){sum(x)})==0)
rmv.rows.crep3 = which(apply(crep3,1,function(x){sum(x)})==0)
rmv.rows.rrep1 = which(apply(rrep1,1,function(x){sum(x)})==0)
rmv.rows.rrep2 = which(apply(rrep2,1,function(x){sum(x)})==0)
rmv.rows.rrep3 = which(apply(rrep3,1,function(x){sum(x)})==0)

allzero=c()
allzero=sort(unique(append(allzero, c(rmv.rows.crep1,rmv.rows.crep2, rmv.rows.crep3, rmv.rows.rrep1, rmv.rows.rrep2, rmv.rows.rrep3))))

ctrl.matrix=ctrl.matrix[-allzero,]
rnase.matrix=rnase.matrix[-allzero,]

#1.3 Normalization
ctrl.frc1=cbind(ctrl.matrix[,1:3])
ctrl.frc2=cbind(ctrl.matrix[,4:6])
ctrl.frc3=cbind(ctrl.matrix[,7:9])
ctrl.frc4=cbind(ctrl.matrix[,10:12])
ctrl.frc5=cbind(ctrl.matrix[,13:15])
ctrl.frc6=cbind(ctrl.matrix[,16:18])
ctrl.frc7=cbind(ctrl.matrix[,19:21])
ctrl.frc8=cbind(ctrl.matrix[,22:24])
ctrl.frc9=cbind(ctrl.matrix[,25:27])
ctrl.frc10=cbind(ctrl.matrix[,28:30])
ctrl.frc11=cbind(ctrl.matrix[,31:33])
ctrl.frc12=cbind(ctrl.matrix[,34:36])
ctrl.frc13=cbind(ctrl.matrix[,37:39])
ctrl.frc14=cbind(ctrl.matrix[,40:42])
ctrl.frc15=cbind(ctrl.matrix[,43:45])
ctrl.frc16=cbind(ctrl.matrix[,46:48])
ctrl.frc17=cbind(ctrl.matrix[,49:51])
ctrl.frc18=cbind(ctrl.matrix[,52:54])
ctrl.frc19=cbind(ctrl.matrix[,55:57])
ctrl.frc20=cbind(ctrl.matrix[,58:60])
ctrl.frc21=cbind(ctrl.matrix[,61:63])
ctrl.frc22=cbind(ctrl.matrix[,64:66])
ctrl.frc23=cbind(ctrl.matrix[,67:69])
ctrl.frc24=cbind(ctrl.matrix[,70:72])
ctrl.frc25=cbind(ctrl.matrix[,73:75])

rnase.frc1=cbind(rnase.matrix[,1:3])
rnase.frc2=cbind(rnase.matrix[,4:6])
rnase.frc3=cbind(rnase.matrix[,7:9])
rnase.frc4=cbind(rnase.matrix[,10:12])
rnase.frc5=cbind(rnase.matrix[,13:15])
rnase.frc6=cbind(rnase.matrix[,16:18])
rnase.frc7=cbind(rnase.matrix[,19:21])
rnase.frc8=cbind(rnase.matrix[,22:24])
rnase.frc9=cbind(rnase.matrix[,25:27])
rnase.frc10=cbind(rnase.matrix[,28:30])
rnase.frc11=cbind(rnase.matrix[,31:33])
rnase.frc12=cbind(rnase.matrix[,34:36])
rnase.frc13=cbind(rnase.matrix[,37:39])
rnase.frc14=cbind(rnase.matrix[,40:42])
rnase.frc15=cbind(rnase.matrix[,43:45])
rnase.frc16=cbind(rnase.matrix[,46:48])
rnase.frc17=cbind(rnase.matrix[,49:51])
rnase.frc18=cbind(rnase.matrix[,52:54])
rnase.frc19=cbind(rnase.matrix[,55:57])
rnase.frc20=cbind(rnase.matrix[,58:60])
rnase.frc21=cbind(rnase.matrix[,61:63])
rnase.frc22=cbind(rnase.matrix[,64:66])
rnase.frc23=cbind(rnase.matrix[,67:69])
rnase.frc24=cbind(rnase.matrix[,70:72])
rnase.frc25=cbind(rnase.matrix[,73:75])

#mean von rep1, rep2, rep3
mean.ctrl.frc1=apply(ctrl.frc1,2,function(x){mean(x)})
mean.ctrl.frc2=apply(ctrl.frc2,2,function(x){mean(x)})
mean.ctrl.frc3=apply(ctrl.frc3,2,function(x){mean(x)})
mean.ctrl.frc4=apply(ctrl.frc4,2,function(x){mean(x)})
mean.ctrl.frc5=apply(ctrl.frc5,2,function(x){mean(x)})
mean.ctrl.frc6=apply(ctrl.frc6,2,function(x){mean(x)})
mean.ctrl.frc7=apply(ctrl.frc7,2,function(x){mean(x)})
mean.ctrl.frc8=apply(ctrl.frc8,2,function(x){mean(x)})
mean.ctrl.frc9=apply(ctrl.frc9,2,function(x){mean(x)})
mean.ctrl.frc10=apply(ctrl.frc10,2,function(x){mean(x)})
mean.ctrl.frc11=apply(ctrl.frc11,2,function(x){mean(x)})
mean.ctrl.frc12=apply(ctrl.frc12,2,function(x){mean(x)})
mean.ctrl.frc13=apply(ctrl.frc13,2,function(x){mean(x)})
mean.ctrl.frc14=apply(ctrl.frc14,2,function(x){mean(x)})
mean.ctrl.frc15=apply(ctrl.frc15,2,function(x){mean(x)})
mean.ctrl.frc16=apply(ctrl.frc16,2,function(x){mean(x)})
mean.ctrl.frc17=apply(ctrl.frc17,2,function(x){mean(x)})
mean.ctrl.frc18=apply(ctrl.frc18,2,function(x){mean(x)})
mean.ctrl.frc19=apply(ctrl.frc19,2,function(x){mean(x)})
mean.ctrl.frc20=apply(ctrl.frc20,2,function(x){mean(x)})
mean.ctrl.frc21=apply(ctrl.frc21,2,function(x){mean(x)})
mean.ctrl.frc22=apply(ctrl.frc22,2,function(x){mean(x)})
mean.ctrl.frc23=apply(ctrl.frc23,2,function(x){mean(x)})
mean.ctrl.frc24=apply(ctrl.frc24,2,function(x){mean(x)})
mean.ctrl.frc25=apply(ctrl.frc25,2,function(x){mean(x)})

mean.rnase.frc1=apply(rnase.frc1,2,function(x){mean(x)})
mean.rnase.frc2=apply(rnase.frc2,2,function(x){mean(x)})
mean.rnase.frc3=apply(rnase.frc3,2,function(x){mean(x)})
mean.rnase.frc4=apply(rnase.frc4,2,function(x){mean(x)})
mean.rnase.frc5=apply(rnase.frc5,2,function(x){mean(x)})
mean.rnase.frc6=apply(rnase.frc6,2,function(x){mean(x)})
mean.rnase.frc7=apply(rnase.frc7,2,function(x){mean(x)})
mean.rnase.frc8=apply(rnase.frc8,2,function(x){mean(x)})
mean.rnase.frc9=apply(rnase.frc9,2,function(x){mean(x)})
mean.rnase.frc10=apply(rnase.frc10,2,function(x){mean(x)})
mean.rnase.frc11=apply(rnase.frc11,2,function(x){mean(x)})
mean.rnase.frc12=apply(rnase.frc12,2,function(x){mean(x)})
mean.rnase.frc13=apply(rnase.frc13,2,function(x){mean(x)})
mean.rnase.frc14=apply(rnase.frc14,2,function(x){mean(x)})
mean.rnase.frc15=apply(rnase.frc15,2,function(x){mean(x)})
mean.rnase.frc16=apply(rnase.frc16,2,function(x){mean(x)})
mean.rnase.frc17=apply(rnase.frc17,2,function(x){mean(x)})
mean.rnase.frc18=apply(rnase.frc18,2,function(x){mean(x)})
mean.rnase.frc19=apply(rnase.frc19,2,function(x){mean(x)})
mean.rnase.frc20=apply(rnase.frc20,2,function(x){mean(x)})
mean.rnase.frc21=apply(rnase.frc21,2,function(x){mean(x)})
mean.rnase.frc22=apply(rnase.frc22,2,function(x){mean(x)})
mean.rnase.frc23=apply(rnase.frc23,2,function(x){mean(x)})
mean.rnase.frc24=apply(rnase.frc24,2,function(x){mean(x)})
mean.rnase.frc25=apply(rnase.frc25,2,function(x){mean(x)})

#function "small.diff" find reps with smallest difference of the means
norm.mean = function(x) {
  diff.rep1.rep2=abs(x[1]-x[2])
  diff.rep1.rep3=abs(x[1]-x[3])
  diff.rep2.rep3=abs(x[2]-x[3])
  
  if(diff.rep1.rep2<diff.rep1.rep3 && diff.rep1.rep2<diff.rep2.rep3) {
    #print("rep1 and rep2")
    mean(c(x[1],x[2]))
  }else if (diff.rep1.rep3<diff.rep1.rep2 && diff.rep1.rep3<diff.rep2.rep3) {
  #print("rep1 and rep3")
  mean(c(x[1],x[3]))
} else { 
 # print("rep2 and rep3")
  mean(c(x[2],x[3]))
  }
}

#compute normalization factor 
norm.fact.ctrl.frc1=norm.mean(mean.ctrl.frc1)/mean.ctrl.frc1
norm.fact.ctrl.frc2=norm.mean(mean.ctrl.frc2)/mean.ctrl.frc2
norm.fact.ctrl.frc3=norm.mean(mean.ctrl.frc3)/mean.ctrl.frc3
norm.fact.ctrl.frc4=norm.mean(mean.ctrl.frc4)/mean.ctrl.frc4
norm.fact.ctrl.frc5=norm.mean(mean.ctrl.frc5)/mean.ctrl.frc5
norm.fact.ctrl.frc6=norm.mean(mean.ctrl.frc6)/mean.ctrl.frc6
norm.fact.ctrl.frc7=norm.mean(mean.ctrl.frc7)/mean.ctrl.frc7
norm.fact.ctrl.frc8=norm.mean(mean.ctrl.frc8)/mean.ctrl.frc8
norm.fact.ctrl.frc9=norm.mean(mean.ctrl.frc9)/mean.ctrl.frc9
norm.fact.ctrl.frc10=norm.mean(mean.ctrl.frc10)/mean.ctrl.frc10
norm.fact.ctrl.frc11=norm.mean(mean.ctrl.frc11)/mean.ctrl.frc11
norm.fact.ctrl.frc12=norm.mean(mean.ctrl.frc12)/mean.ctrl.frc12
norm.fact.ctrl.frc13=norm.mean(mean.ctrl.frc13)/mean.ctrl.frc13
norm.fact.ctrl.frc14=norm.mean(mean.ctrl.frc14)/mean.ctrl.frc14
norm.fact.ctrl.frc15=norm.mean(mean.ctrl.frc15)/mean.ctrl.frc15
norm.fact.ctrl.frc16=norm.mean(mean.ctrl.frc16)/mean.ctrl.frc16
norm.fact.ctrl.frc17=norm.mean(mean.ctrl.frc17)/mean.ctrl.frc17
norm.fact.ctrl.frc18=norm.mean(mean.ctrl.frc18)/mean.ctrl.frc18
norm.fact.ctrl.frc19=norm.mean(mean.ctrl.frc19)/mean.ctrl.frc19
norm.fact.ctrl.frc20=norm.mean(mean.ctrl.frc20)/mean.ctrl.frc20
norm.fact.ctrl.frc21=norm.mean(mean.ctrl.frc21)/mean.ctrl.frc21
norm.fact.ctrl.frc22=norm.mean(mean.ctrl.frc22)/mean.ctrl.frc22
norm.fact.ctrl.frc23=norm.mean(mean.ctrl.frc23)/mean.ctrl.frc23
norm.fact.ctrl.frc24=norm.mean(mean.ctrl.frc24)/mean.ctrl.frc24
norm.fact.ctrl.frc25=norm.mean(mean.ctrl.frc25)/mean.ctrl.frc25

norm.fact.rnase.frc1=norm.mean(mean.rnase.frc1)/mean.rnase.frc1
norm.fact.rnase.frc2=norm.mean(mean.rnase.frc2)/mean.rnase.frc2
norm.fact.rnase.frc3=norm.mean(mean.rnase.frc3)/mean.rnase.frc3
norm.fact.rnase.frc4=norm.mean(mean.rnase.frc4)/mean.rnase.frc4
norm.fact.rnase.frc5=norm.mean(mean.rnase.frc5)/mean.rnase.frc5
norm.fact.rnase.frc6=norm.mean(mean.rnase.frc6)/mean.rnase.frc6
norm.fact.rnase.frc7=norm.mean(mean.rnase.frc7)/mean.rnase.frc7
norm.fact.rnase.frc8=norm.mean(mean.rnase.frc8)/mean.rnase.frc8
norm.fact.rnase.frc9=norm.mean(mean.rnase.frc9)/mean.rnase.frc9
norm.fact.rnase.frc10=norm.mean(mean.rnase.frc10)/mean.rnase.frc10
norm.fact.rnase.frc11=norm.mean(mean.rnase.frc11)/mean.rnase.frc11
norm.fact.rnase.frc12=norm.mean(mean.rnase.frc12)/mean.rnase.frc12
norm.fact.rnase.frc13=norm.mean(mean.rnase.frc13)/mean.rnase.frc13
norm.fact.rnase.frc14=norm.mean(mean.rnase.frc14)/mean.rnase.frc14
norm.fact.rnase.frc15=norm.mean(mean.rnase.frc15)/mean.rnase.frc15
norm.fact.rnase.frc16=norm.mean(mean.rnase.frc16)/mean.rnase.frc16
norm.fact.rnase.frc17=norm.mean(mean.rnase.frc17)/mean.rnase.frc17
norm.fact.rnase.frc18=norm.mean(mean.rnase.frc18)/mean.rnase.frc18
norm.fact.rnase.frc19=norm.mean(mean.rnase.frc19)/mean.rnase.frc19
norm.fact.rnase.frc20=norm.mean(mean.rnase.frc20)/mean.rnase.frc20
norm.fact.rnase.frc21=norm.mean(mean.rnase.frc21)/mean.rnase.frc21
norm.fact.rnase.frc22=norm.mean(mean.rnase.frc22)/mean.rnase.frc22
norm.fact.rnase.frc23=norm.mean(mean.rnase.frc23)/mean.rnase.frc23
norm.fact.rnase.frc24=norm.mean(mean.rnase.frc24)/mean.rnase.frc24
norm.fact.rnase.frc25=norm.mean(mean.rnase.frc25)/mean.rnase.frc25

#normed values 
norm.ctrl.frc1=data.frame(mapply('*', ctrl.frc1, norm.fact.ctrl.frc1, SIMPLIFY=FALSE))
norm.ctrl.frc2=data.frame(mapply('*', ctrl.frc2, norm.fact.ctrl.frc2, SIMPLIFY=FALSE))
norm.ctrl.frc3=data.frame(mapply('*', ctrl.frc3, norm.fact.ctrl.frc3, SIMPLIFY=FALSE))
norm.ctrl.frc4=data.frame(mapply('*', ctrl.frc4, norm.fact.ctrl.frc4, SIMPLIFY=FALSE))
norm.ctrl.frc5=data.frame(mapply('*', ctrl.frc5, norm.fact.ctrl.frc5, SIMPLIFY=FALSE))
norm.ctrl.frc6=data.frame(mapply('*', ctrl.frc6, norm.fact.ctrl.frc6, SIMPLIFY=FALSE))
norm.ctrl.frc7=data.frame(mapply('*', ctrl.frc7, norm.fact.ctrl.frc7, SIMPLIFY=FALSE))
norm.ctrl.frc8=data.frame(mapply('*', ctrl.frc8, norm.fact.ctrl.frc8, SIMPLIFY=FALSE))
norm.ctrl.frc9=data.frame(mapply('*', ctrl.frc9, norm.fact.ctrl.frc9, SIMPLIFY=FALSE))
norm.ctrl.frc10=data.frame(mapply('*', ctrl.frc10, norm.fact.ctrl.frc10, SIMPLIFY=FALSE))
norm.ctrl.frc11=data.frame(mapply('*', ctrl.frc11, norm.fact.ctrl.frc11, SIMPLIFY=FALSE))
norm.ctrl.frc12=data.frame(mapply('*', ctrl.frc12, norm.fact.ctrl.frc12, SIMPLIFY=FALSE))
norm.ctrl.frc13=data.frame(mapply('*', ctrl.frc13, norm.fact.ctrl.frc13, SIMPLIFY=FALSE))
norm.ctrl.frc14=data.frame(mapply('*', ctrl.frc14, norm.fact.ctrl.frc14, SIMPLIFY=FALSE))
norm.ctrl.frc15=data.frame(mapply('*', ctrl.frc15, norm.fact.ctrl.frc15, SIMPLIFY=FALSE))
norm.ctrl.frc16=data.frame(mapply('*', ctrl.frc16, norm.fact.ctrl.frc16, SIMPLIFY=FALSE))
norm.ctrl.frc17=data.frame(mapply('*', ctrl.frc17, norm.fact.ctrl.frc17, SIMPLIFY=FALSE))
norm.ctrl.frc18=data.frame(mapply('*', ctrl.frc18, norm.fact.ctrl.frc18, SIMPLIFY=FALSE))
norm.ctrl.frc19=data.frame(mapply('*', ctrl.frc19, norm.fact.ctrl.frc19, SIMPLIFY=FALSE))
norm.ctrl.frc20=data.frame(mapply('*', ctrl.frc20, norm.fact.ctrl.frc20, SIMPLIFY=FALSE))
norm.ctrl.frc21=data.frame(mapply('*', ctrl.frc21, norm.fact.ctrl.frc21, SIMPLIFY=FALSE))
norm.ctrl.frc22=data.frame(mapply('*', ctrl.frc22, norm.fact.ctrl.frc22, SIMPLIFY=FALSE))
norm.ctrl.frc23=data.frame(mapply('*', ctrl.frc23, norm.fact.ctrl.frc23, SIMPLIFY=FALSE))
norm.ctrl.frc24=data.frame(mapply('*', ctrl.frc24, norm.fact.ctrl.frc24, SIMPLIFY=FALSE))
norm.ctrl.frc25=data.frame(mapply('*', ctrl.frc25, norm.fact.ctrl.frc25, SIMPLIFY=FALSE))

norm.rnase.frc1=data.frame(mapply('*', rnase.frc1, norm.fact.rnase.frc1, SIMPLIFY=FALSE))
norm.rnase.frc2=data.frame(mapply('*', rnase.frc2, norm.fact.rnase.frc2, SIMPLIFY=FALSE))
norm.rnase.frc3=data.frame(mapply('*', rnase.frc3, norm.fact.rnase.frc3, SIMPLIFY=FALSE))
norm.rnase.frc4=data.frame(mapply('*', rnase.frc4, norm.fact.rnase.frc4, SIMPLIFY=FALSE))
norm.rnase.frc5=data.frame(mapply('*', rnase.frc5, norm.fact.rnase.frc5, SIMPLIFY=FALSE))
norm.rnase.frc6=data.frame(mapply('*', rnase.frc6, norm.fact.rnase.frc6, SIMPLIFY=FALSE))
norm.rnase.frc7=data.frame(mapply('*', rnase.frc7, norm.fact.rnase.frc7, SIMPLIFY=FALSE))
norm.rnase.frc8=data.frame(mapply('*', rnase.frc8, norm.fact.rnase.frc8, SIMPLIFY=FALSE))
norm.rnase.frc9=data.frame(mapply('*', rnase.frc9, norm.fact.rnase.frc9, SIMPLIFY=FALSE))
norm.rnase.frc10=data.frame(mapply('*', rnase.frc10, norm.fact.rnase.frc10, SIMPLIFY=FALSE))
norm.rnase.frc11=data.frame(mapply('*', rnase.frc11, norm.fact.rnase.frc11, SIMPLIFY=FALSE))
norm.rnase.frc12=data.frame(mapply('*', rnase.frc12, norm.fact.rnase.frc12, SIMPLIFY=FALSE))
norm.rnase.frc13=data.frame(mapply('*', rnase.frc13, norm.fact.rnase.frc13, SIMPLIFY=FALSE))
norm.rnase.frc14=data.frame(mapply('*', rnase.frc14, norm.fact.rnase.frc14, SIMPLIFY=FALSE))
norm.rnase.frc15=data.frame(mapply('*', rnase.frc15, norm.fact.rnase.frc15, SIMPLIFY=FALSE))
norm.rnase.frc16=data.frame(mapply('*', rnase.frc16, norm.fact.rnase.frc16, SIMPLIFY=FALSE))
norm.rnase.frc17=data.frame(mapply('*', rnase.frc17, norm.fact.rnase.frc17, SIMPLIFY=FALSE))
norm.rnase.frc18=data.frame(mapply('*', rnase.frc18, norm.fact.rnase.frc18, SIMPLIFY=FALSE))
norm.rnase.frc19=data.frame(mapply('*', rnase.frc19, norm.fact.rnase.frc19, SIMPLIFY=FALSE))
norm.rnase.frc20=data.frame(mapply('*', rnase.frc20, norm.fact.rnase.frc20, SIMPLIFY=FALSE))
norm.rnase.frc21=data.frame(mapply('*', rnase.frc21, norm.fact.rnase.frc21, SIMPLIFY=FALSE))
norm.rnase.frc22=data.frame(mapply('*', rnase.frc22, norm.fact.rnase.frc22, SIMPLIFY=FALSE))
norm.rnase.frc23=data.frame(mapply('*', rnase.frc23, norm.fact.rnase.frc23, SIMPLIFY=FALSE))
norm.rnase.frc24=data.frame(mapply('*', rnase.frc24, norm.fact.rnase.frc24, SIMPLIFY=FALSE))
norm.rnase.frc25=data.frame(mapply('*', rnase.frc25, norm.fact.rnase.frc25, SIMPLIFY=FALSE))


#organize the different samples
condition <- factor(rep(c("ctrl1","rnase1","ctrl2","rnase2","ctrl3","rnase3"),25))

# create vectors containing norm values of fraction 1 to 25
norm.ctrl1 <- cbind(norm.ctrl.frc1[1],norm.ctrl.frc2[1],norm.ctrl.frc3[1],norm.ctrl.frc4[1],norm.ctrl.frc5[1],norm.ctrl.frc6[1],norm.ctrl.frc7[1],norm.ctrl.frc8[1],norm.ctrl.frc9[1],norm.ctrl.frc10[1],norm.ctrl.frc11[1],norm.ctrl.frc12[1],norm.ctrl.frc13[1],norm.ctrl.frc14[1],norm.ctrl.frc15[1],norm.ctrl.frc16[1],norm.ctrl.frc17[1],norm.ctrl.frc18[1],norm.ctrl.frc19[1],norm.ctrl.frc20[1],norm.ctrl.frc21[1],norm.ctrl.frc22[1],norm.ctrl.frc23[1],norm.ctrl.frc24[1],norm.ctrl.frc25[1])

norm.ctrl2 <- cbind(norm.ctrl.frc1[2],norm.ctrl.frc2[2],norm.ctrl.frc3[2],norm.ctrl.frc4[2],norm.ctrl.frc5[2],norm.ctrl.frc6[2],norm.ctrl.frc7[2],norm.ctrl.frc8[2],norm.ctrl.frc9[2],norm.ctrl.frc10[2],norm.ctrl.frc11[2],norm.ctrl.frc12[2],norm.ctrl.frc13[2],norm.ctrl.frc14[2],norm.ctrl.frc15[2],norm.ctrl.frc16[2],norm.ctrl.frc17[2],norm.ctrl.frc18[2],norm.ctrl.frc19[2],norm.ctrl.frc20[2],norm.ctrl.frc21[2],norm.ctrl.frc22[2],norm.ctrl.frc23[2],norm.ctrl.frc24[2],norm.ctrl.frc25[2])

norm.ctrl3 <- cbind(norm.ctrl.frc1[3],norm.ctrl.frc2[3],norm.ctrl.frc3[3],norm.ctrl.frc4[3],norm.ctrl.frc5[3],norm.ctrl.frc6[3],norm.ctrl.frc7[3],norm.ctrl.frc8[3],norm.ctrl.frc9[3],norm.ctrl.frc10[3],norm.ctrl.frc11[3],norm.ctrl.frc12[3],norm.ctrl.frc13[3],norm.ctrl.frc14[3],norm.ctrl.frc15[3],norm.ctrl.frc16[3],norm.ctrl.frc17[3],norm.ctrl.frc18[3],norm.ctrl.frc19[3],norm.ctrl.frc20[3],norm.ctrl.frc21[3],norm.ctrl.frc22[3],norm.ctrl.frc23[3],norm.ctrl.frc24[3],norm.ctrl.frc25[3])

norm.rnase1 <- cbind(norm.rnase.frc1[1],norm.rnase.frc2[1],norm.rnase.frc3[1],norm.rnase.frc4[1],norm.rnase.frc5[1],norm.rnase.frc6[1],norm.rnase.frc7[1],norm.rnase.frc8[1],norm.rnase.frc9[1],norm.rnase.frc10[1],norm.rnase.frc11[1],norm.rnase.frc12[1],norm.rnase.frc13[1],norm.rnase.frc14[1],norm.rnase.frc15[1],norm.rnase.frc16[1],norm.rnase.frc17[1],norm.rnase.frc18[1],norm.rnase.frc19[1],norm.rnase.frc20[1],norm.rnase.frc21[1],norm.rnase.frc22[1],norm.rnase.frc23[1],norm.rnase.frc24[1],norm.rnase.frc25[1])

norm.rnase2 <- cbind(norm.rnase.frc1[2],norm.rnase.frc2[2],norm.rnase.frc3[2],norm.rnase.frc4[2],norm.rnase.frc5[2],norm.rnase.frc6[2],norm.rnase.frc7[2],norm.rnase.frc8[2],norm.rnase.frc9[2],norm.rnase.frc10[2],norm.rnase.frc11[2],norm.rnase.frc12[2],
norm.rnase.frc13[2],norm.rnase.frc14[2],norm.rnase.frc15[2],norm.rnase.frc16[2],norm.rnase.frc17[2],norm.rnase.frc18[2],norm.rnase.frc19[2],norm.rnase.frc20[2],norm.rnase.frc21[2],norm.rnase.frc22[2],norm.rnase.frc23[2],norm.rnase.frc24[2],norm.rnase.frc25[2])

norm.rnase3 <- cbind(norm.rnase.frc1[3],norm.rnase.frc2[3],norm.rnase.frc3[3],norm.rnase.frc4[3],norm.rnase.frc5[3],norm.rnase.frc6[3],norm.rnase.frc7[3],norm.rnase.frc8[3],norm.rnase.frc9[3],norm.rnase.frc10[3],norm.rnase.frc11[3],norm.rnase.frc12[3],norm.rnase.frc13[3],norm.rnase.frc14[3],norm.rnase.frc15[3],norm.rnase.frc16[3],norm.rnase.frc17[3],norm.rnase.frc18[3],norm.rnase.frc19[3],norm.rnase.frc20[3],norm.rnase.frc21[3],norm.rnase.frc22[3],norm.rnase.frc23[3],norm.rnase.frc24[3],norm.rnase.frc25[3])

#Kurve smoothen 

for (j in 1:nrow(norm.ctrl1))
  for (i in 2:24)
   norm.ctrl1[j,i]=mean(c(norm.ctrl1[j,i-1],norm.ctrl1[j,i], norm.ctrl1[j,i+1]))

for (j in 1:nrow(norm.ctrl2))
  for (i in 2:24)
   norm.ctrl2[j,i]=mean(c(norm.ctrl2[j,i-1],norm.ctrl2[j,i], norm.ctrl2[j,i+1]))

for (j in 1:nrow(norm.ctrl3))
  for (i in 2:24)
   norm.ctrl3[j,i]=mean(c(norm.ctrl3[j,i-1],norm.ctrl3[j,i], norm.ctrl3[j,i+1]))

for (j in 1:nrow(norm.rnase1))
  for (i in 2:24)
   norm.rnase1[j,i]=mean(c(norm.rnase1[j,i-1],norm.rnase1[j,i], norm.rnase1[j,i+1]))

for (j in 1:nrow(norm.rnase2))
  for (i in 2:24)
   norm.rnase2[j,i]=mean(c(norm.rnase2[j,i-1],norm.rnase2[j,i], norm.rnase2[j,i+1]))

for (j in 1:nrow(norm.rnase3))
  for (i in 2:24)
   norm.rnase3[j,i]=mean(c(norm.rnase3[j,i-1],norm.rnase3[j,i], norm.rnase3[j,i+1]))



# normalization smaple 1ctrl
datanormctrl1 <- as.data.frame(norm.ctrl1)

for (i in 1:nrow(datanormctrl1)) {
  x <- sum(datanormctrl1[i, ]) / 100
  datanormctrl1[i, ] = datanormctrl1[i, ] / x
}

rownames(datanormctrl1)=rownames(ctrl.matrix)

# normalization sample 2ctrl
datanormctrl2 <- as.data.frame(norm.ctrl2)

for (i in 1:nrow(datanormctrl2)) {
  x <- sum(datanormctrl2[i, ]) / 100
  datanormctrl2[i, ] = datanormctrl2[i, ] / x
}

rownames(datanormctrl2)=rownames(ctrl.matrix)

# normalization sample 3ctrl

datanormctrl3 <- as.data.frame(norm.ctrl3)

for (i in 1:nrow(datanormctrl3)) {
  x <- sum(datanormctrl3[i, ]) / 100
  datanormctrl3[i, ] = datanormctrl3[i, ] / x
}

rownames(datanormctrl3)=rownames(ctrl.matrix)

#normalization sample 1 rnase

datanormrnase1 <- as.data.frame(norm.rnase1)

for (i in 1:nrow(datanormrnase1)){
  x <- sum(datanormrnase1[i, ])/ 100
  datanormrnase1[i, ] = datanormrnase1[i, ] / x
}

rownames(datanormrnase1)=rownames(rnase.matrix)

#normalization sample 2 rnase

datanormrnase2 <- as.data.frame(norm.rnase2)

for (i in 1:nrow(datanormrnase2)) {
  x <- sum(datanormrnase2[i, ]) /100
  datanormrnase2[i, ] = datanormrnase2[i, ] / x
}

rownames(datanormrnase2)=rownames(rnase.matrix)

#normalization sample3 rnase

datanormrnase3 <- as.data.frame(norm.rnase3)

for (i in 1:nrow(datanormrnase3)) {
  x <- sum(datanormrnase3[i, ]) / 100
  datanormrnase3[i, ] = datanormrnase3[i, ] / x
}

rownames(datanormrnase3)=rownames(rnase.matrix)


##Correlation for Reproducibility 
datac1=t(datanormctrl1)
datac2=t(datanormctrl2)
datac3=t(datanormctrl3)
datar1=t(datanormrnase1)
datar2=t(datanormrnase2)
datar3=t(datanormrnase3)

#ANZAHL AN PROTEINE = 4732
#leere Vektoren erstellen 

#klappt nur für protein 1-4000. danach anscheinend std =0 -> intervall nach hinten schieben, evt ohne transponieren
r=0.7

ctrl12=c()
ctrl13=c()
ctrl23=c()
rnase12=c()
rnase13=c()
rnase23=c()

low.cor=function(x,a,b){
  for (i in 1:ncol(datac1)){
    x=append(x, (cor(a[,i], b[,i])))
  }
   r=0.7
   which(x<=r)
}

low.cor(ctrl12,datac1, datac2)
low.cor(ctrl13,datac1, datac3)
low.cor(ctrl23,datac2, datac3)
low.cor(rnase12,datar1, datar2)
low.cor(rnase13,datar1, datar3)
low.cor(rnase23,datar2, datar3)

ctrl.low.cor=c()
ctrl.low.cor=sort(append(ctrl.low.cor,c(low.cor(ctrl12,datac1, datac2),low.cor(ctrl13,datac1, datac3),low.cor(ctrl23,datac2, datac3))))

rnase.low.cor=c()
rnase.low.cor=sort(append(rnase.low.cor,c(low.cor(rnase12,datar1, datar2),low.cor(rnase13,datar1, datar3),low.cor(rnase23,datar2, datar3))))


rmv.low.cor=unique(c(ctrl.low.cor,rnase.low.cor))
#81 proteins deleted --> 4676 proteins left


rmv.low.cor.ctrl=c()
for ( i in 1:nrow(as.data.frame(table(ctrl.low.cor))))
if(as.data.frame(table(ctrl.low.cor))[i,2]>1){
  rmv.low.cor.ctrl=append(rmv.low.cor.ctrl, as.data.frame(table(ctrl.low.cor))[i,1])
}

rmv.low.cor.rnase=c()
for ( i in 1:nrow(as.data.frame(table(rnase.low.cor))))
if(as.data.frame(table(rnase.low.cor))[i,2]>1){
  rmv.low.cor.rnase=append(rmv.low.cor.rnase, as.data.frame(table(rnase.low.cor))[i,1])
}


rmv.low.cor=c()
rmv.low.cor=unique(append(rmv.low.cor,c(rmv.low.cor.ctrl,rmv.low.cor.rnase)))
as.numeric(as.vector(rmv.low.cor))

# wie viele punkte einbeziehen
#erster und letzter wert 
# diff(sign(diff)) ??
# wie unterscheiden global vs lokal 
# wie maxima? gröster wert oder größter peak 


rmv.low.cor=unique(c(ctrl.low.cor,rnase.low.cor))
#81 proteins deleted --> 4676 proteins left

datanormctrl1=datanormctrl1[-as.numeric(as.vector(rmv.low.cor)),]
datanormctrl2=datanormctrl2[-as.numeric(as.vector(rmv.low.cor)),]
datanormctrl3=datanormctrl3[-as.numeric(as.vector(rmv.low.cor)),]
datanormrnase1=datanormrnase1[-as.numeric(as.vector(rmv.low.cor)),]
datanormrnase2=datanormrnase2[-as.numeric(as.vector(rmv.low.cor)),]
datanormrnase3=datanormrnase3[-as.numeric(as.vector(rmv.low.cor)),]

# erster skalierungsschritt wichtig! selbe proteingesamtmenge pro versuch, keine verhältnisse einbeziehen!!
# für jede franktion summe der 3 reps gleich?
```

```{r}

#Mean of three reps to create one dataframe for control and rnase seperately
mean.rep.ctrl=datanormctrl1
for (j in 1:nrow(datanormctrl1)){
  for (i in 1:25){
  mean.rep.ctrl[j,i]=mean(c(datanormctrl1[j,i],datanormctrl2[j,i], datanormctrl3[j,i]))
}}

mean.rep.rnase=datanormrnase1
for (j in 1:nrow(datanormrnase1)){
  for (i in 1:25){
  mean.rep.rnase[j,i]=mean(c(datanormrnase1[j,i],datanormrnase2[j,i], datanormrnase3[j,i]))
}}


```

```{r}
#2. Finding Maxima
#2.1 Finding position of maxima peaks

# We define a function that takes a protein from our normalized dataframes and goes through each value, comparing it to m values before and m values after (m being an adjustable parameter, which allows for heightened robustness against outliers/fluctuation)

#Unser Code
find_peaks <- function(x, m=50) { #in this case m was set to m=2 to start off, but will be adjusted accordingly after first results
  peaks_pos <- sapply(1:length(x), FUN = function(i) {
    if (x[i] == 0) return (numeric(0))
    lborder <- max(c(1, i-m))
    rborder <- min(c(i+m, length(x)))
    if(all(x[lborder:rborder] <= x[i])) return(i) else return(numeric(0))
                      }
               )
  return(unlist(peaks_pos))
}

#Function to only list those peaks above a certain threshold (in this case 3/3% since our data is normalized to 100%)

find_sig_peaks <- function(x, threshold = 3) {
        apply(x, 1, function(x) {
          peaks <- find_peaks(x)
          peaks <- peaks[x[peaks] > threshold]
          unlist(peaks)
          peaks
             }
        )
}


 
 #T-Test Abweichungen ausgleichen bei vielen T-tests für die einzelne Proteine

```
```{r}
#compute difference between rnase and control group to indicate left, right or no shift



peaks.ctrl = find_sig_peaks(mean.rep.ctrl, threshold = 3) 
peaks.rnase = find_sig_peaks(mean.rep.rnase, threshold = 3)

peaks.ctrl.mtrx <- as.matrix(peaks.ctrl)
peaks.rnase.mtrx <- as.matrix(peaks.rnase)

peaks.ctrl.unlist <- unlist(peaks.ctrl.mtrx, use.names = TRUE)
peaks.rnase.unlist <- unlist(peaks.rnase.mtrx)


#shift <- c()
#for (i in length(peaks.ctrl.mtrx)) {
#append(shift, as.numeric(peaks.ctrl.mtrx[i]) - as.numeric(peaks.rnase.mtrx[i]))
#}
shift <- peaks.ctrl.unlist - peaks.rnase.unlist
a = c()

dgfffb <- for (i in 1:nrow(shift)) {
            if (shift[i] > 0) {
                a <- c(a,"left shift")
             } else if (shift[i] < 0) {
                a <- c(a,"right shift")
            } else {
                a <-c(a,"no shift")
            }
}
# erstes element löschen
# wie viele identifiziert, wie viele überlappen

# cbind to creeate new coloumn for shift information

#4656 proteins left 
peaks.ctrl = find_sig_peaks(mean.rep.ctrl, threshold = 3) 
peaks.rnase = find_sig_peaks(mean.rep.rnase, threshold = 3)
peak.ctrl1= find_sig_peaks(datanormctrl1, threshold=3)
peak.ctrl2= find_sig_peaks(datanormctrl2, threshold=3)
peak.ctrl3= find_sig_peaks(datanormctrl3, threshold=3)
peak.rnase1= find_sig_peaks(datanormrnase1, threshold=3)
peak.rnase2= find_sig_peaks(datanormrnase2, threshold=3)
peak.rnase3= find_sig_peaks(datanormrnase3, threshold=3)

peaks.ctrl.mtrx <- unlist(as.matrix(peaks.ctrl))
peaks.rnase.mtrx <- unlist(as.matrix(peaks.rnase))
peaks.ctrl1.mtrx = unlist(as.matrix(peak.ctrl1))
peaks.ctrl2.mtrx = unlist(as.matrix(peak.ctrl2))
peaks.ctrl3.mtrx = unlist(as.matrix(peak.ctrl3))
peaks.rnase1.mtrx = unlist(as.matrix(peak.rnase1))
peaks.rnase2.mtrx = unlist(as.matrix(peak.rnase2))
peaks.rnase3.mtrx = unlist(as.matrix(peak.rnase3))

peaks.mtrx=cbind(peaks.ctrl1.mtrx, peaks.ctrl2.mtrx, peaks.ctrl3.mtrx, peaks.rnase1.mtrx, peaks.rnase2.mtrx, peaks.rnase3.mtrx)

shift.mean=peaks.ctrl.mtrx-peaks.rnase.mtrx
shift.mtrx1=peaks.ctrl1.mtrx-peaks.rnase1.mtrx
shift.mtrx2=peaks.ctrl2.mtrx-peaks.rnase2.mtrx
shift.mtrx3=peaks.ctrl3.mtrx-peaks.rnase3.mtrx

#Identify RNA-dependent proteins by creating matrix with only proteins with a left shift -> negative values in shift.mean
#matrix should include the original row names of the RDPs
rnames=rownames(shift.mean)
RDP.name=c()
RDP.pos=c()
for (i in 1:nrow(shift.mean)){
if(shift.mean[i]<0){
  RDP.name=append(RDP.name,rnames[i])
  RDP.pos=append(RDP.pos, i)
}}
RDP.matrix=cbind(RDP.name, RDP.pos) #

# cbind to create new coloumn for shift information
color=c()
peaks.allg=cbind(peaks.ctrl.mtrx, peaks.rnase.mtrx,shift.mean)
for ( i in 1:nrow(peaks.allg)){
  if (peaks.allg[i,3]>0){
    color=append(color,c("green"))
  }else if (peaks.allg[i,3]<0){
    color=append(color,c("pink"))
  }else{
    color=append(color, c("blue"))
  }
}
peaks.allg=cbind(peaks.allg, color)
#k-means 
g=cbind(peaks.ctrl.mtrx,peaks.rnase.mtrx)
clus=kmeans(g, 3)
fviz_cluster(clus,g, xlab=TRUE, ylab=TRUE, geom="point")
shift.mean["MIEN1_HUMAN",]
shift.mean["TEN1_HUMAN",]
peaks.ctrl.mtrx["ZN622_HUMAN",]
peaks.rnase.mtrx["ZN622_HUMAN",]
#selber geplottet 
#in Report: wenige punkte, weil proteine aufeinander sind, suche Bsp.
plot.new()
plot(peaks.allg[,1],peaks.allg[,2], type="p", lwd=1, col=color, pch=19)
abline(coef=c(0,1), col="red")


#t-tests
pval <- c()
sigproteins <- c()

for (i in 1:nrow(peaks.mtrx)) {
  ctrl.vec1 <- datanormctrl1[i, peaks.mtrx[i,1]]
  ctrl.vec2 <- datanormctrl2[i, peaks.mtrx[i,2]]
  ctrl.vec3 <- datanormctrl3[i, peaks.mtrx[i,3]]
  ctrl.vec <- c(ctrl.vec1, ctrl.vec2, ctrl.vec3)
  
  rnase.vec1 <- datanormrnase1[i, peaks.mtrx[i,1]]
  rnase.vec2 <- datanormrnase2[i, peaks.mtrx[i,2]]
  rnase.vec3 <- datanormrnase3[i, peaks.mtrx[i,3]]
  rnase.vec <- c(rnase.vec1, rnase.vec2, rnase.vec3)
    #test <- wilcox.test(ctrl.vec, rnase.vec, paired=TRUE, exact=TRUE, alternative = "two.sided")
 # pval <- append(pval, test$p.value)
  if  ((ctrl.vec[1] == ctrl.vec[2]) | (ctrl.vec[2] == ctrl.vec[3]) | (rnase.vec[1] == rnase.vec[2]) |        (rnase.vec[2] == rnase.vec[3]) | ctrl.vec[1] == rnase.vec[1]){
    pval <- append(pval,1)
  } else {ttest <- t.test(ctrl.vec, rnase.vec)
  pval <- append(pval, ttest$p.value)}
}

pval.adj=p.adjust(pval, method = "BH", n = length(pval))
for (i in 1:length(pval.adj)){
  if (pval.adj[i] < 0.05) {
    sigproteins <- append(sigproteins, rnames[i]) #length(sigproteins)=1921
  } }

#find similar proteins between sigproteins and RDP.matrix. sigproteins contains also right-shifted proteins that are not RDPs, those will be eliminated. Also only RDPs with a significant shift will be chosen.
sig.RDP=c()
for (i in 1:length(sigproteins)){
  for (j in 1:nrow(RDP.matrix)){
    if(sigproteins[i]==RDP.matrix[j,1]){
      sig.RDP=append(sig.RDP,RDP.matrix[j])   #length(similar.ttest)=401
    }}}


#k-means and testing with silhouette plot
#clustering with 2 clusters

mtrx.kmeans=cbind(peaks.ctrl.mtrx,peaks.rnase.mtrx)

clus2=kmeans(mtrx.kmeans, 2)
fviz_cluster(clus2,mtrx.kmeans, xlab=TRUE, ylab=TRUE, geom="point")
sil2=fviz_silhouette(silhouette(clus2$cluster, dist(mtrx.kmeans)))
sil2 <- mtrx.kmeans %>% dist(.) %>% silhouette(clus2$cluster, .)
sil2.data <- data.frame(cluster = factor(sil2[, 1]), sil_width = sil2[, 3])
mean.sil2.width=mean(sil2.data$sil_width)

#clustering with 3 clusters
clus3=kmeans(mtrx.kmeans, 3)
fviz_cluster(clus3,mtrx.kmeans, xlab=TRUE, ylab=TRUE, geom="point")
fviz_silhouette(silhouette(clus3$cluster, dist(mtrx.kmeans)))
sil3=fviz_silhouette(silhouette(clus3$cluster, dist(mtrx.kmeans)))
sil3 <- mtrx.kmeans %>% dist(.) %>% silhouette(clus3$cluster, .)
sil3.data <- data.frame(cluster = factor(sil3[, 1]), sil_width = sil3[, 3])
mean.sil3.width=mean(sil3.data$sil_width)

#clustering with 4 clusters 
clus4=kmeans(mtrx.kmeans, 4)
fviz_cluster(clus4,mtrx.kmeans, xlab=TRUE, ylab=TRUE, geom="point")
fviz_silhouette(silhouette(clus4$cluster, dist(mtrx.kmeans)))
sil4=fviz_silhouette(silhouette(clus4$cluster, dist(mtrx.kmeans)))
sil4 <- mtrx.kmeans %>% dist(.) %>% silhouette(clus4$cluster, .)
sil4.data <- data.frame(cluster = factor(sil4[, 1]), sil_width = sil4[, 3])
mean.sil4.width=mean(sil4.data$sil_width)

#clustering with 5 clusters 
clus5=kmeans(mtrx.kmeans, 5)
fviz_cluster(clus5,mtrx.kmeans,xlab="Max Control",ylab="Max RNase", geom="point")
fviz_silhouette(silhouette(clus5$cluster, dist(mtrx.kmeans)))
sil5=fviz_silhouette(silhouette(clus5$cluster, dist(mtrx.kmeans)))
sil5 <- mtrx.kmeans %>% dist(.) %>% silhouette(clus5$cluster, .)
sil5.data <- data.frame(cluster = factor(sil5[, 1]), sil_width = sil5[, 3])
mean.sil5.width=mean(sil5.data$sil_width)

#clustering with 6 clusters
clus6=kmeans(mtrx.kmeans, 6)
fviz_cluster(clus6,mtrx.kmeans, xlab=TRUE, ylab=TRUE, geom="point")
fviz_silhouette(silhouette(clus6$cluster, dist(mtrx.kmeans)))
sil6=fviz_silhouette(silhouette(clus6$cluster, dist(mtrx.kmeans)))
sil6 <- mtrx.kmeans %>% dist(.) %>% silhouette(clus6$cluster, .)
sil6.data <- data.frame(cluster = factor(sil6[, 1]), sil_width = sil6[, 3])
mean.sil6.width=mean(sil6.data$sil_width)

#elbow-plot
k.max <- 15
data <- mtrx.kmeans
wss <- sapply(1:k.max, 
              function(k){kmeans(data,k, nstart=50,iter.max = 15 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of Clusters k",
     ylab="Total Within-Clusters Sum of Squares", col="blue")

#selber geplottet 
#in Report: wenige punkte, weil proteine aufeinander sind, suche Bsp.
color=c()
peaks.allg=cbind(peaks.ctrl.mtrx, peaks.rnase.mtrx,shift.mean)
for ( i in 1:nrow(peaks.allg)){
  if (peaks.allg[i,3]>0){
    color=append(color,c("green"))
  }else if (peaks.allg[i,3]<0){
    color=append(color,c("pink"))
  }else{
    color=append(color, c("blue"))
  }
}
peaks.allg=cbind(peaks.allg, color)
plot.new()
plot(peaks.allg[,1],peaks.allg[,2], type="p", lwd=1, col=color, pch=19)
abline(coef=c(0,1), col="red")

#Linear Regression 
#model with protein 1-4190 (90%)
corlm=c()
t.mean.rep.ctrl=t(mean.rep.ctrl)
t.mean.rep.rnase=t(mean.rep.rnase)

  for (i in 1:(0.9*ncol(t.mean.rep.ctrl))){
    corlm=append(corlm, (cor(t.mean.rep.ctrl[,i], t.mean.rep.rnase[,i])))
  }

lm.data=data.frame(abs(shift.mean[1:(0.9*ncol(t.mean.rep.ctrl))]),corlm)
colnames(lm.data)=c("Shift", "Corr")

model=lm(Shift ~ Corr, data=lm.data)
summary(model)
model$coefficients
cor.model=model$coefficients[2]*est.shift + model$coefficients[1]

#try how the model works for the last 10% 

cor.model=c()
for (i in (0.9*ncol(t.mean.rep.ctrl)):ncol(t.mean.rep.ctrl)){
cor.model=append(cor.model, cor(t.mean.rep.ctrl[,i], t.mean.rep.rnase[,i]))
}
est.shift=(cor.model-model$coefficients[1])/model$coefficients[2]

```

