---
title: "Bioinfoprojekt HeLa cells"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
MS_Table <- read.table("/Users/sinakuhnel/Desktop/Uni 1/FS4/Bioinfoprojekt/RDeeP_HeLa_NS.csv", header=TRUE, row.names=1, sep = ";")

#str(MS_Table)
#subset( MS_Table, subset= var(x,y = NULL))
```

```{r}
#1. Clean Up and Normalization
#1.1 Split dataset into 2 datasets. One dataset consists only of Control group and the other of RNase.

ctrl_matrix= cbind(MS_Table[, seq(1,150,2)])
rnase_matrix=cbind(MS_Table[, seq(1,150,2)])

#1.2 Removing all zero rows
ctrl_matrix[rowSums(ctrl_matrix[])>0,]
rnase_matrix[rowSums(rnase_matrix[])>0,]

#1.3 Normalization
#Loopen mit sapply
ctrl.frc1=cbind(ctrl_matrix[,1:3])
ctrl.frc2=cbind(ctrl_matrix[,4:6])
ctrl.frc3=cbind(ctrl_matrix[,7:9])
ctrl.frc4=cbind(ctrl_matrix[,10:12])
ctrl.frc5=cbind(ctrl_matrix[,13:15])
ctrl.frc6=cbind(ctrl_matrix[,16:18])
ctrl.frc7=cbind(ctrl_matrix[,19:21])
ctrl.frc8=cbind(ctrl_matrix[,22:24])
ctrl.frc9=cbind(ctrl_matrix[,25:27])
ctrl.frc10=cbind(ctrl_matrix[,28:30])
ctrl.frc11=cbind(ctrl_matrix[,31:33])
ctrl.frc12=cbind(ctrl_matrix[,34:36])
ctrl.frc13=cbind(ctrl_matrix[,37:39])
ctrl.frc14=cbind(ctrl_matrix[,40:42])
ctrl.frc15=cbind(ctrl_matrix[,43:45])
ctrl.frc16=cbind(ctrl_matrix[,46:48])
ctrl.frc17=cbind(ctrl_matrix[,49:51])
ctrl.frc18=cbind(ctrl_matrix[,52:54])
ctrl.frc19=cbind(ctrl_matrix[,55:57])
ctrl.frc20=cbind(ctrl_matrix[,58:60])
ctrl.frc21=cbind(ctrl_matrix[,61:63])
ctrl.frc22=cbind(ctrl_matrix[,64:66])
ctrl.frc23=cbind(ctrl_matrix[,67:69])
ctrl.frc24=cbind(ctrl_matrix[,70:72])
ctrl.frc25=cbind(ctrl_matrix[,73:75])

#mean von rep1, rep2, rep3
mean.ctrl.frc1=apply(ctrl.frc1,2,function(x){mean(x)})
mean.ctrl.frc2=apply(ctrl.frc2,2,function(x){mean(x)})
mean.ctrl.frc3=apply(ctrl.frc3,2,function(x){mean(x)})
mean.ctrl.frc4=apply(ctrl.frc4,2,function(x){mean(x)})
mean.ctrl.frc5=apply(ctrl.frc5,2,function(x){mean(x)})
mean.ctrl.frc6=apply(ctrl.frc6,2,function(x){mean(x)})
mean.ctrl.frc7=apply(ctrl.frc7,2,function(x){mean(x)})
mean.ctrl.frc8=apply(ctrl.frc8,2,function(x){mean(x)})
mean.ctrl.frc9=apply(ctrl.frc9,2,function(x){mean(x)})
mean.ctrl.frc10=apply(ctrl.frc10,2,function(x){mean(x)})
mean.ctrl.frc11=apply(ctrl.frc11,2,function(x){mean(x)})
mean.ctrl.frc12=apply(ctrl.frc12,2,function(x){mean(x)})
mean.ctrl.frc13=apply(ctrl.frc13,2,function(x){mean(x)})
mean.ctrl.frc14=apply(ctrl.frc14,2,function(x){mean(x)})
mean.ctrl.frc15=apply(ctrl.frc15,2,function(x){mean(x)})
mean.ctrl.frc16=apply(ctrl.frc16,2,function(x){mean(x)})
mean.ctrl.frc17=apply(ctrl.frc17,2,function(x){mean(x)})
mean.ctrl.frc18=apply(ctrl.frc18,2,function(x){mean(x)})
mean.ctrl.frc19=apply(ctrl.frc19,2,function(x){mean(x)})
mean.ctrl.frc20=apply(ctrl.frc20,2,function(x){mean(x)})
mean.ctrl.frc21=apply(ctrl.frc21,2,function(x){mean(x)})
mean.ctrl.frc22=apply(ctrl.frc22,2,function(x){mean(x)})
mean.ctrl.frc23=apply(ctrl.frc23,2,function(x){mean(x)})
mean.ctrl.frc24=apply(ctrl.frc24,2,function(x){mean(x)})
mean.ctrl.frc25=apply(ctrl.frc25,2,function(x){mean(x)})

#function "small.diff" find reps with smallest difference of the means
norm.mean = function(x) {
  diff.rep1.rep2=abs(x[1]-x[2])
  diff.rep1.rep3=abs(x[1]-x[3])
  diff.rep2.rep3=abs(x[2]-x[3])
  
  if(diff.rep1.rep2<diff.rep1.rep3 && diff.rep1.rep2<diff.rep2.rep3) {
    #print("rep1 and rep2")
    mean(c(x[1],x[2]))
  }else if (diff.rep1.rep3<diff.rep1.rep2 && diff.rep1.rep3<diff.rep2.rep3) {
  #print("rep1 and rep3")
  mean(c(x[1],x[3]))
} else { 
 # print("rep2 and rep3")
  mean(c(x[2],x[3]))
  }
}

#compute normalization factor 
norm.fact.ctrl.frc1=norm.mean(mean.ctrl.frc1)/mean.ctrl.frc1
norm.fact.ctrl.frc2=norm.mean(mean.ctrl.frc2)/mean.ctrl.frc2
norm.fact.ctrl.frc3=norm.mean(mean.ctrl.frc3)/mean.ctrl.frc3
norm.fact.ctrl.frc4=norm.mean(mean.ctrl.frc4)/mean.ctrl.frc4
norm.fact.ctrl.frc5=norm.mean(mean.ctrl.frc5)/mean.ctrl.frc5
norm.fact.ctrl.frc6=norm.mean(mean.ctrl.frc6)/mean.ctrl.frc6
norm.fact.ctrl.frc7=norm.mean(mean.ctrl.frc7)/mean.ctrl.frc7
norm.fact.ctrl.frc8=norm.mean(mean.ctrl.frc8)/mean.ctrl.frc8
norm.fact.ctrl.frc9=norm.mean(mean.ctrl.frc9)/mean.ctrl.frc9
norm.fact.ctrl.frc10=norm.mean(mean.ctrl.frc10)/mean.ctrl.frc10
norm.fact.ctrl.frc11=norm.mean(mean.ctrl.frc11)/mean.ctrl.frc11
norm.fact.ctrl.frc12=norm.mean(mean.ctrl.frc12)/mean.ctrl.frc12
norm.fact.ctrl.frc13=norm.mean(mean.ctrl.frc13)/mean.ctrl.frc13
norm.fact.ctrl.frc14=norm.mean(mean.ctrl.frc14)/mean.ctrl.frc14
norm.fact.ctrl.frc15=norm.mean(mean.ctrl.frc15)/mean.ctrl.frc15
norm.fact.ctrl.frc16=norm.mean(mean.ctrl.frc16)/mean.ctrl.frc16
norm.fact.ctrl.frc17=norm.mean(mean.ctrl.frc17)/mean.ctrl.frc17
norm.fact.ctrl.frc18=norm.mean(mean.ctrl.frc18)/mean.ctrl.frc18
norm.fact.ctrl.frc19=norm.mean(mean.ctrl.frc19)/mean.ctrl.frc19
norm.fact.ctrl.frc20=norm.mean(mean.ctrl.frc20)/mean.ctrl.frc20
norm.fact.ctrl.frc21=norm.mean(mean.ctrl.frc21)/mean.ctrl.frc21
norm.fact.ctrl.frc22=norm.mean(mean.ctrl.frc22)/mean.ctrl.frc22
norm.fact.ctrl.frc23=norm.mean(mean.ctrl.frc23)/mean.ctrl.frc23
norm.fact.ctrl.frc24=norm.mean(mean.ctrl.frc24)/mean.ctrl.frc24
norm.fact.ctrl.frc25=norm.mean(mean.ctrl.frc25)/mean.ctrl.frc25

#normed values for control
norm.ctrl.frc1=ctrl.frc1*norm.fact.ctrl.frc1
norm.ctrl.frc2=ctrl.frc2*norm.fact.ctrl.frc2
norm.ctrl.frc3=ctrl.frc3*norm.fact.ctrl.frc3
norm.ctrl.frc4=ctrl.frc4*norm.fact.ctrl.frc4
norm.ctrl.frc5=ctrl.frc5*norm.fact.ctrl.frc5
norm.ctrl.frc6=ctrl.frc6*norm.fact.ctrl.frc6
norm.ctrl.frc7=ctrl.frc7*norm.fact.ctrl.frc7
norm.ctrl.frc8=ctrl.frc8*norm.fact.ctrl.frc8
norm.ctrl.frc9=ctrl.frc9*norm.fact.ctrl.frc9
norm.ctrl.frc10=ctrl.frc10*norm.fact.ctrl.frc10
norm.ctrl.frc11=ctrl.frc11*norm.fact.ctrl.frc11
norm.ctrl.frc12=ctrl.frc12*norm.fact.ctrl.frc12
norm.ctrl.frc13=ctrl.frc13*norm.fact.ctrl.frc13
norm.ctrl.frc14=ctrl.frc14*norm.fact.ctrl.frc14
norm.ctrl.frc15=ctrl.frc15*norm.fact.ctrl.frc15
norm.ctrl.frc16=ctrl.frc16*norm.fact.ctrl.frc16
norm.ctrl.frc17=ctrl.frc17*norm.fact.ctrl.frc17
norm.ctrl.frc18=ctrl.frc18*norm.fact.ctrl.frc18
norm.ctrl.frc19=ctrl.frc19*norm.fact.ctrl.frc19
norm.ctrl.frc20=ctrl.frc20*norm.fact.ctrl.frc20
norm.ctrl.frc21=ctrl.frc21*norm.fact.ctrl.frc21
norm.ctrl.frc22=ctrl.frc22*norm.fact.ctrl.frc22
norm.ctrl.frc23=ctrl.frc23*norm.fact.ctrl.frc23
norm.ctrl.frc24=ctrl.frc24*norm.fact.ctrl.frc24
norm.ctrl.frc25=ctrl.frc25*norm.fact.ctrl.frc25

```

```{r}
#the same steps with the rnase table
rnase.frc1=cbind(rnase_matrix[,1:3])
rnase.frc2=cbind(rnase_matrix[,4:6])
rnase.frc3=cbind(rnase_matrix[,7:9])
rnase.frc4=cbind(rnase_matrix[,10:12])
rnase.frc5=cbind(rnase_matrix[,13:15])
rnase.frc6=cbind(rnase_matrix[,16:18])
rnase.frc7=cbind(rnase_matrix[,19:21])
rnase.frc8=cbind(rnase_matrix[,22:24])
rnase.frc9=cbind(rnase_matrix[,25:27])
rnase.frc10=cbind(rnase_matrix[,28:30])
rnase.frc11=cbind(rnase_matrix[,31:33])
rnase.frc12=cbind(rnase_matrix[,34:36])
rnase.frc13=cbind(rnase_matrix[,37:39])
rnase.frc14=cbind(rnase_matrix[,40:42])
rnase.frc15=cbind(rnase_matrix[,43:45])
rnase.frc16=cbind(rnase_matrix[,46:48])
rnase.frc17=cbind(rnase_matrix[,49:51])
rnase.frc18=cbind(rnase_matrix[,52:54])
rnase.frc19=cbind(rnase_matrix[,55:57])
rnase.frc20=cbind(rnase_matrix[,58:60])
rnase.frc21=cbind(rnase_matrix[,61:63])
rnase.frc22=cbind(rnase_matrix[,64:66])
rnase.frc23=cbind(rnase_matrix[,67:69])
rnase.frc24=cbind(rnase_matrix[,70:72])
rnase.frc25=cbind(rnase_matrix[,73:75])


#mean von rep1, rep2, rep3
mean.rnase.frc1=apply(rnase.frc1,2,function(x){mean(x)})
mean.rnase.frc2=apply(rnase.frc2,2,function(x){mean(x)})
mean.rnase.frc3=apply(rnase.frc3,2,function(x){mean(x)})
mean.rnase.frc4=apply(rnase.frc4,2,function(x){mean(x)})
mean.rnase.frc5=apply(rnase.frc5,2,function(x){mean(x)})
mean.rnase.frc6=apply(rnase.frc6,2,function(x){mean(x)})
mean.rnase.frc7=apply(rnase.frc7,2,function(x){mean(x)})
mean.rnase.frc8=apply(rnase.frc8,2,function(x){mean(x)})
mean.rnase.frc9=apply(rnase.frc9,2,function(x){mean(x)})
mean.rnase.frc10=apply(rnase.frc10,2,function(x){mean(x)})
mean.rnase.frc11=apply(rnase.frc11,2,function(x){mean(x)})
mean.rnase.frc12=apply(rnase.frc12,2,function(x){mean(x)})
mean.rnase.frc13=apply(rnase.frc13,2,function(x){mean(x)})
mean.rnase.frc14=apply(rnase.frc14,2,function(x){mean(x)})
mean.rnase.frc15=apply(rnase.frc15,2,function(x){mean(x)})
mean.rnase.frc16=apply(rnase.frc16,2,function(x){mean(x)})
mean.rnase.frc17=apply(rnase.frc17,2,function(x){mean(x)})
mean.rnase.frc18=apply(rnase.frc18,2,function(x){mean(x)})
mean.rnase.frc19=apply(rnase.frc19,2,function(x){mean(x)})
mean.rnase.frc20=apply(rnase.frc20,2,function(x){mean(x)})
mean.rnase.frc21=apply(rnase.frc21,2,function(x){mean(x)})
mean.rnase.frc22=apply(rnase.frc22,2,function(x){mean(x)})
mean.rnase.frc23=apply(rnase.frc23,2,function(x){mean(x)})
mean.rnase.frc24=apply(rnase.frc24,2,function(x){mean(x)})
mean.rnase.frc25=apply(rnase.frc25,2,function(x){mean(x)})



#compute normalization factor 
norm.fact.rnase.frc1=norm.mean(mean.rnase.frc1)/mean.rnase.frc1
norm.fact.rnase.frc2=norm.mean(mean.rnase.frc2)/mean.rnase.frc2
norm.fact.rnase.frc3=norm.mean(mean.rnase.frc3)/mean.rnase.frc3
norm.fact.rnase.frc4=norm.mean(mean.rnase.frc4)/mean.rnase.frc4
norm.fact.rnase.frc5=norm.mean(mean.rnase.frc5)/mean.rnase.frc5
norm.fact.rnase.frc6=norm.mean(mean.rnase.frc6)/mean.rnase.frc6
norm.fact.rnase.frc7=norm.mean(mean.rnase.frc7)/mean.rnase.frc7
norm.fact.rnase.frc8=norm.mean(mean.rnase.frc8)/mean.rnase.frc8
norm.fact.rnase.frc9=norm.mean(mean.rnase.frc9)/mean.rnase.frc9
norm.fact.rnase.frc10=norm.mean(mean.rnase.frc10)/mean.rnase.frc10
norm.fact.rnase.frc11=norm.mean(mean.rnase.frc11)/mean.rnase.frc11
norm.fact.rnase.frc12=norm.mean(mean.rnase.frc12)/mean.rnase.frc12
norm.fact.rnase.frc13=norm.mean(mean.rnase.frc13)/mean.rnase.frc13
norm.fact.rnase.frc14=norm.mean(mean.rnase.frc14)/mean.rnase.frc14
norm.fact.rnase.frc15=norm.mean(mean.rnase.frc15)/mean.rnase.frc15
norm.fact.rnase.frc16=norm.mean(mean.rnase.frc16)/mean.rnase.frc16
norm.fact.rnase.frc17=norm.mean(mean.rnase.frc17)/mean.rnase.frc17
norm.fact.rnase.frc18=norm.mean(mean.rnase.frc18)/mean.rnase.frc18
norm.fact.rnase.frc19=norm.mean(mean.rnase.frc19)/mean.rnase.frc19
norm.fact.rnase.frc20=norm.mean(mean.rnase.frc20)/mean.rnase.frc20
norm.fact.rnase.frc21=norm.mean(mean.rnase.frc21)/mean.rnase.frc21
norm.fact.rnase.frc22=norm.mean(mean.rnase.frc22)/mean.rnase.frc22
norm.fact.rnase.frc23=norm.mean(mean.rnase.frc23)/mean.rnase.frc23
norm.fact.rnase.frc24=norm.mean(mean.rnase.frc24)/mean.rnase.frc24
norm.fact.rnase.frc25=norm.mean(mean.rnase.frc25)/mean.rnase.frc25



#normed values for rnase
norm.rnase.frc1=rnase.frc1*norm.fact.rnase.frc1
norm.rnase.frc2=rnase.frc2*norm.fact.rnase.frc2
norm.rnase.frc3=rnase.frc3*norm.fact.rnase.frc3
norm.rnase.frc4=rnase.frc4*norm.fact.rnase.frc4
norm.rnase.frc5=rnase.frc5*norm.fact.rnase.frc5
norm.rnase.frc6=rnase.frc6*norm.fact.rnase.frc6
norm.rnase.frc7=rnase.frc7*norm.fact.rnase.frc7
norm.rnase.frc8=rnase.frc8*norm.fact.rnase.frc8
norm.rnase.frc9=rnase.frc9*norm.fact.rnase.frc9
norm.rnase.frc10=rnase.frc10*norm.fact.rnase.frc10
norm.rnase.frc11=rnase.frc11*norm.fact.rnase.frc11
norm.rnase.frc12=rnase.frc12*norm.fact.rnase.frc12
norm.rnase.frc13=rnase.frc13*norm.fact.rnase.frc13
norm.rnase.frc14=rnase.frc14*norm.fact.rnase.frc14
norm.rnase.frc15=rnase.frc15*norm.fact.rnase.frc15
norm.rnase.frc16=rnase.frc16*norm.fact.rnase.frc16
norm.rnase.frc17=rnase.frc17*norm.fact.rnase.frc17
norm.rnase.frc18=rnase.frc18*norm.fact.rnase.frc18
norm.rnase.frc19=rnase.frc19*norm.fact.rnase.frc19
norm.rnase.frc20=rnase.frc20*norm.fact.rnase.frc20
norm.rnase.frc21=rnase.frc21*norm.fact.rnase.frc21
norm.rnase.frc22=rnase.frc22*norm.fact.rnase.frc22
norm.rnase.frc23=rnase.frc23*norm.fact.rnase.frc23
norm.rnase.frc24=rnase.frc24*norm.fact.rnase.frc24
norm.rnase.frc25=rnase.frc25*norm.fact.rnase.frc25

```




```{r}
#organize the different samples
condition <- factor(rep(c("ctrl1","rnase1","ctrl2","rnase2","ctrl3","rnase3"),25))
# define subtables for each condition
data.ctrl1 <- data$condition =="ctrl1"
data.ctrl2 <- data$condition =="ctrl2"
data.ctrl3 <- data$condition =="ctrl3"
data.rnase1 <- data$condition =="rnase1"
data.rnase2 <- data$condition =="rnase2"
data.rnase3 <- data$condition =="rnase3"

# create vectors containing norm values of fraction 1 to 25
norm.ctrl1 <- c(norm.ctrl.frc1[1],norm.ctrl.frc2[1],norm.ctrl.frc3[1],norm.ctrl.frc4[1],norm.ctrl.frc5[1],norm.ctrl.frc6[1],norm.ctrl.frc7[1],norm.ctrl.frc8[1],norm.ctrl.frc9[1],norm.ctrl.frc10[1],norm.ctrl.frc11[1],norm.ctrl.frc12[1],norm.ctrl.frc13[1],norm.ctrl.frc14[1],norm.ctrl.frc15[1],norm.ctrl.frc16[1],norm.ctrl.frc17[1],norm.ctrl.frc18[1],norm.ctrl.frc19[1],norm.ctrl.frc20[1],norm.ctrl.frc21[1],norm.ctrl.frc22[1],norm.ctrl.frc23[1],norm.ctrl.frc24[1],norm.ctrl.frc25[1])

norm.ctrl2 <- c(norm.ctrl.frc1[2],norm.ctrl.frc2[2],norm.ctrl.frc3[2],norm.ctrl.frc4[2],norm.ctrl.frc5[2],norm.ctrl.frc6[2],norm.ctrl.frc7[2],norm.ctrl.frc8[2],norm.ctrl.frc9[2],norm.ctrl.frc10[2],norm.ctrl.frc11[2],norm.ctrl.frc12[2],norm.ctrl.frc13[2],norm.ctrl.frc14[2],norm.ctrl.frc15[2],norm.ctrl.frc16[2],norm.ctrl.frc17[2],norm.ctrl.frc18[2],norm.ctrl.frc19[2],norm.ctrl.frc20[2],norm.ctrl.frc21[2],norm.ctrl.frc22[2],norm.ctrl.frc23[2],norm.ctrl.frc24[2],norm.ctrl.frc25[2])

norm.ctrl3 <- c(norm.ctrl.frc1[3],norm.ctrl.frc2[3],norm.ctrl.frc3[3],norm.ctrl.frc4[3],norm.ctrl.frc5[3],norm.ctrl.frc6[3],norm.ctrl.frc7[3],norm.ctrl.frc8[3],norm.ctrl.frc9[3],norm.ctrl.frc10[3],norm.ctrl.frc11[3],norm.ctrl.frc12[3],norm.ctrl.frc13[3],norm.ctrl.frc14[3],norm.ctrl.frc15[3],norm.ctrl.frc16[3],norm.ctrl.frc17[3],norm.ctrl.frc18[3],norm.ctrl.frc19[3],norm.ctrl.frc20[3],norm.ctrl.frc21[3],norm.ctrl.frc22[3],norm.ctrl.frc23[3],norm.ctrl.frc24[3],norm.ctrl.frc25[3])

norm.rnase1 <- c(norm.rnase.frc1[1],norm.rnase.frc2[1],norm.rnase.frc3[1],norm.rnase.frc4[1],norm.rnase.frc5[1],norm.rnase.frc6[1],norm.rnase.frc7[1],norm.rnase.frc8[1],norm.rnase.frc9[1],norm.rnase.frc10[1],norm.rnase.frc11[1],norm.rnase.frc12[1],norm.rnase.frc13[1],norm.rnase.frc14[1],norm.rnase.frc15[1],norm.rnase.frc16[1],norm.rnase.frc17[1],norm.rnase.frc18[1],norm.rnase.frc19[1],norm.rnase.frc20[1],norm.rnase.frc21[1],norm.rnase.frc22[1],norm.rnase.frc23[1],norm.rnase.frc24[1],norm.rnase.frc25[1])

norm.rnase2 <- c(norm.rnase.frc1[2],norm.rnase.frc2[2],norm.rnase.frc3[2],norm.rnase.frc4[2],norm.rnase.frc5[2],norm.rnase.frc6[2],norm.rnase.frc7[2],norm.rnase.frc8[2],norm.rnase.frc9[2],norm.rnase.frc10[2],norm.rnase.frc11[2],norm.rnase.frc12[2],
norm.rnase.frc13[2],norm.rnase.frc14[2],norm.rnase.frc15[2],norm.rnase.frc16[2],norm.rnase.frc17[2],norm.rnase.frc18[2],norm.rnase.frc19[2],norm.rnase.frc20[2],norm.rnase.frc21[2],norm.rnase.frc22[2],norm.rnase.frc23[2],norm.rnase.frc24[2],norm.rnase.frc25[2])

norm.rnase3 <- c(norm.rnase.frc1[3],norm.rnase.frc2[3],norm.rnase.frc3[3],norm.rnase.frc4[3],norm.rnase.frc5[3],norm.rnase.frc6[3],norm.rnase.frc7[3],norm.rnase.frc8[3],norm.rnase.frc9[3],norm.rnase.frc10[3],norm.rnase.frc11[3],norm.rnase.frc12[3],norm.rnase.frc13[3],norm.rnase.frc14[3],norm.rnase.frc15[3],norm.rnase.frc16[3],norm.rnase.frc17[3],norm.rnase.frc18[3],norm.rnase.frc19[3],norm.rnase.frc20[3],norm.rnase.frc21[3],norm.rnase.frc22[3],norm.rnase.frc23[3],norm.rnase.frc24[3],norm.rnase.frc25[3])

as.data.frame(norm.ctrl1)


# normalization over the sum of 100% 
for (i in 1:4765) {
  x <- sum(xx)/ 100
  xxx= xx/ x
}
1:nrow(xx)

xx = as.matrix(Matrixctrl1)

Matrixctrl1 <- cbind(norm.ctrl1[["Fraction1_Ctrl_Rep1"]],norm.ctrl1[["Fraction2_Ctrl_Rep1"]],norm.ctrl1[["Fraction3_Ctrl_Rep1"]],norm.ctrl1[["Fraction4_Ctrl_Rep1"]],norm.ctrl1[["Fraction5_Ctrl_Rep1"]],norm.ctrl1[["Fraction6_Ctrl_Rep1"]],norm.ctrl1[["Fraction7_Ctrl_Rep1"]],norm.ctrl1[["Fraction8_Ctrl_Rep1"]],norm.ctrl1[["Fraction9_Ctrl_Rep1"]],norm.ctrl1[["Fraction10_Ctrl_Rep1"]],norm.ctrl1[["Fraction11_Ctrl_Rep1"]],norm.ctrl1[["Fraction12_Ctrl_Rep1"]],norm.ctrl1[["Fraction13_Ctrl_Rep1"]],norm.ctrl1[["Fraction14_Ctrl_Rep1"]],norm.ctrl1[["Fraction15_Ctrl_Rep1"]],norm.ctrl1[["Fraction16_Ctrl_Rep1"]],norm.ctrl1[["Fraction17_Ctrl_Rep1"]],norm.ctrl1[["Fraction18_Ctrl_Rep1"]],norm.ctrl1[["Fraction19_Ctrl_Rep1"]],norm.ctrl1[["Fraction20_Ctrl_Rep1"]],norm.ctrl1[["Fraction21_Ctrl_Rep1"]],norm.ctrl1[["Fraction22_Ctrl_Rep1"]],norm.ctrl1[["Fraction23_Ctrl_Rep1"]],norm.ctrl1[["Fraction24_Ctrl_Rep1"]],norm.ctrl1[["Fraction25_Ctrl_Rep1"]])

View(xxx)
barplot(xxx)
```


```

