---
title: "HeLa_NS_Project"
author: "Greta Pick"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

MS_Table <- read.table("/Users/gretapick/Documents/Studium/4. Semester/Bioinformatik/RDeeP_HeLa_NS.csv", header=TRUE, row.names=1, sep = ";")

#1. Clean Up and Normalization
#1.1 Split dataset into 2 datasets. One dataset consists only of Control group and the other of RNase.

ctrl_matrix= cbind(MS_Table[, seq(1,150,2)])
ctrl_matrix
rnase_matrix=cbind(MS_Table[1:10, seq(1,150,2)])
rnase_matrix

#1.2 Normalization

#von allen Proteinen von rep1, rep2 und rep3 von fraction1 den mean nehmen
rep1=c(ctrl_matrix[,1])
mean_rep1=mean(rep1)
mean(rep1)

rep2=c(ctrl_matrix[,2])
mean_rep2=mean(rep2)
mean(rep2)

rep3=c(ctrl_matrix[,3])
mean_rep3=mean(rep3)
mean(rep3)

#bestimme die 2 reps (deren mean) mit dem geringesten Abstand zueinander und berechne aus denen 2 den "best_mean"
diff_mean1_mean2=abs(mean_rep1-mean_rep2)
diff_mean1_mean3=abs(mean_rep1-mean_rep3)
diff_mean2_mean3=abs(mean_rep2-mean_rep3)

best_mean <-if(diff_mean1_mean2<diff_mean1_mean3 && diff_mean1_mean2<diff_mean2_mean3) {
  print("rep1 and rep2")
  mean(c(ctrl_matrix[,1],(ctrl_matrix[,2])))
} else if (diff_mean1_mean3<diff_mean1_mean2 && diff_mean1_mean3<diff_mean2_mean3) {
  print("rep1 and rep3")
  mean(c(ctrl_matrix[,1],(ctrl_matrix[,3])))
} else { 
  print("rep2 and rep3")
  mean(c(ctrl_matrix[,2],(ctrl_matrix[,3])))
}
best_mean


#determine normalization factor for every replicate for fraction 1
norm_fact_rep1 = best_mean/mean_rep1
norm_fact_rep2 = best_mean/mean_rep2
norm_fact_rep3 = best_mean/mean_rep3

#new value for CTRL fraction 1 for rep1, rep2 and rep3
new_rep1 = ctrl_matrix[,1]*norm_fact_rep1
new_rep2 = ctrl_matrix[,2]*norm_fact_rep2
new_rep3 = ctrl_matrix[,3]*norm_fact_rep3

```


```{r}

```



